---
apiVersion: v1
kind: Service
metadata:
  name: gatus-waf
  namespace: gatus
  labels:
    app.kubernetes.io/name: gatus-waf
    app.kubernetes.io/instance: gatus-waf-${ENVIRONMENT}
    app.kubernetes.io/version: "4.25.0"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
  selector:
    app: gatus-waf
    node: worker
