---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-freenas-config
  namespace: storage
  labels:
    app: truenas
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: democratic-csi-freenas-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          instance_id: null
          httpConnection:
            protocol: ${TRUENAS_PROTOCOL}
            host: ${TRUENAS_HOST}
            port: ${TRUENAS_PORT}
            allowInsecure: ${ALLOW_INSECURE}
            apiVersion: 2
            apiKey: "{{ .TRUENAS_API_KEY }}"
          zfs:
            datasetParentName: ${DATASET_PARENT}
            detachedSnapshotsDatasetParentName: ${DATASET_SNAPSHOTS}
            zvolCompression: "on"
            zvolDedup: null
            zvolEnableReservation: false
            zvolBlocksize: null
          iscsi:
            targetPortal: ${TRUENAS_ISCSI_PORTAL}
            interface: null
            namePrefix: csi-
            nameSuffix: -k8s
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 7
                targetGroupAuthType: None
                targetGroupAuthGroup: null
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: SSD
            extentAvailThreshold: 0
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: truenas_api_creds
        property: credential
